
services:
  app:
    build: ./server  # serverディレクトリをビルドコンテキストとして指定
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=production
    volumes:
      # terraformディレクトリをコンテナ内部にマウント
      - ./terraform:/terraform
