services:
  app:
    build: ./server  # serverディレクトリをビルドコンテキストとして指定
    # ports:
    #   - "8080:8080"
    environment:
      - GO_ENV=production
      - DISCORD_WEBHOOK_URL="https://discord.com/api/webhooks/xxxx/yyyy"
    volumes:
      # terraformディレクトリをコンテナ内部にマウント
      - ./terraform:/terraform

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./nginx/certs/server.crt:/etc/nginx/certs/server.crt
      - ./nginx/certs/server.key:/etc/nginx/certs/server.key
    depends_on:
      - app
